name: cw-pbb-worker ci/cd pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up the things
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Installing dependencies
        run: npm install

      - name: Building the source code
        run: npm run build

      - name: Quality gate analysis
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_SECRET }}
          SONAR_HOST_URL: ${{ vars.SONARQUBE_HOST }}
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.host.url=${SONAR_HOST_URL}
            -Dsonar.token=${SONARQUBE_TOKEN}
            -Dsonar.qualitygate.wait=true

      - name: Preparing the development image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PORT: ${{ secrets.DEV_PORT }}
        run: |
          docker build --build-arg PORT=${PORT} -t cw-pbb-worker-dev .
          docker tag cw-pbb-worker-dev ${DOCKER_USERNAME}/cw-pbb-worker-dev:latest

      - name: Publishing the development image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_SECRET }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker push ${DOCKER_USERNAME}/cw-pbb-worker-dev:latest

      - name: Preparing the production image
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION}}
          GH_PWD: ${{ secrets.GH_SECRET }}
          GH_USERNAME: ${{ vars.GH_USERNAME }}
          PORT: ${{ secrets.PROD_PORT }}
        run: |
          docker build --build-arg PORT=${PORT} -t ${DOCKER_USERNAME}/cw-pbb-worker:${VITE_APP_VERSION} -t ghcr.io/${GH_USERNAME}/cw-pbb-worker:${VITE_APP_VERSION} .

      - name: Publishing the production image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_SECRET }}
          VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION}}
          GH_PWD: ${{ secrets.GH_SECRET }}
          GH_USERNAME: ${{ vars.GH_USERNAME }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        run: |
          echo "Logging and pushing the image to DockerHub"

          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker push ${DOCKER_USERNAME}/cw-pbb-worker:${VITE_APP_VERSION}

          echo "Logging and pushing the image to GHCR"

          docker login ghcr.io -u ${GH_USERNAME} -p ${GH_PWD}
          docker push ghcr.io/${GH_USERNAME}/cw-pbb-worker:${VITE_APP_VERSION}

      - name: Deploying the code to development server
        env:
          CAPROVER_HOST: ${{ secrets.CAPROVER_HOST }}
          CAPROVER_PWD: ${{ secrets.CAPROVER_PWD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npm install -g caprover
          caprover deploy \
          --host ${CAPROVER_HOST} \
          -p ${CAPROVER_PWD} \
          --imageName ${DOCKER_USERNAME}/cw-pbb-worker-dev:latest \
          --appName cw-pbb-worker-dev

      - name: Deploying the code to production server
        env:
          VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          CAPROVER_PROD_HOST: ${{ secrets.CAPROVER_PROD_HOST }}
          CAPROVER_PROD_PWD: ${{ secrets.CAPROVER_PROD_PWD }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        run: |
          npm install -g caprover
          caprover deploy \
          --host ${CAPROVER_PROD_HOST} \
          -p ${CAPROVER_PROD_PWD} \
          --imageName ${DOCKER_USERNAME}/cw-pbb-worker:${VITE_APP_VERSION} \
          --appName cw-pbb-worker
